name: Flutter Web
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Build Web and Deploy
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
          flutter-version: '3.10.x'
      - uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_APP_NAME: ${{secrets.APP_NAME}}
          envkey_OPENAI_KEY: ${{secrets.OPENAI_KEY}}
      - run: flutter config --enable-web
      - run: flutter pub get
      - run: flutter pub run build_runner build --delete-conflicting-outputs
      - run: flutter build web --release
      - run: |
          cd build/web
          git init
          git config --global user.email miguel.luque.97@gmail.com
          git config --global user.name MiguelLuque
          git status
          git remote add origin https://${{secrets.COMMIT_SECRET}}@github.com/MiguelLuque/sherpa-translator.git
          git checkout -b gh-pages
          git add --all
          git commit -m "update"
          git push origin gh-pages -f
